################################################################################################################################################
################################################################################################################################################
# The below section is the General board base code — ESP32-S3 N16R8 Dev Board setup Don't touch or change.
################################################################################################################################################
################################################################################################################################################

esphome:
  name: ${device_internal_name}
  friendly_name: ${device_friendly_name}


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

captive_portal:

logger:

api:
  id: ${device_internal_name}_ha_api
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret web_server_password

improv_serial:

safe_mode:
  disabled: false
  reboot_timeout: 5min
  num_attempts: 5

################################################################################
# Time
################################################################################
time:
  - platform: homeassistant
    id: ${device_internal_name}_internal_time
    timezone: ${region}
  - platform: homeassistant
    id: hass_time

################################################################################
# I2C
################################################################################
i2c:
  - id: ${device_internal_name}_i2c_bus0
    sda: GPIO48
    scl: GPIO47
    scan: true

################################################################################
# UART
################################################################################
uart:
  id: energomonitor_uart 
  rx_pin: 18
  tx_pin: 17
  baud_rate: 9600





################################################################################
# Switches
################################################################################
switch:
  - platform: restart
    id: ${device_internal_name}_device_restart
    name: "Restart"
    web_server:
      sorting_weight: 10    

  - platform: safe_mode
    id: ${device_internal_name}_device_safe_mode
    name: "Use Safe Mode"
    disabled_by_default: true
    web_server:
      sorting_weight: 10    


##################################################################################################################
# Binary Sensors
##################################################################################################################
binary_sensor:
  - platform: status
    id: ${device_internal_name}_status
    name: "Status"
    icon: mdi:network-pos
    disabled_by_default: true
      
